services:
  guardian:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK
    hostname: guardian-0
    ports:
      - "7070:7070"
      - "7071:7071"
    command:
      - ./wait-for-it.sh
      - -t
      - "0"
      - eth2-deploy:2000
      - --
      - /guardiand
      - node
      - --ethRPC
      - ws://eth1:8545
      - --bscRPC
      - ws://eth2:8546
      - --polygonRPC
      - ws://eth1:8545
      - --avalancheRPC
      - ws://eth1:8545
      - --terraWS
      - ws://terra-terrad:26657/websocket
      - --terraLCD
      - http://terra-lcd:1317
      - --terraContract
      - terra18vd8fpwxzck93qlwghaj6arh4p7c5n896xzem5
      - --solanaContract
      - Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o
      - --solanaWS
      - ws://solana-devnet:8900
      - --solanaRPC
      - http://solana-devnet:8899
      - --unsafeDevMode
      - --guardianKey
      - /tmp/bridge.key
      - --publicRPC
      - "[::]:7070"
      - --publicWeb
      - "[::]:7071"
      - --adminSocket
      - /tmp/admin.sock
      - --dataDir
      - /tmp/data
